# Generated by Django 3.0.7 on 2022-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happymap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='xLoc',
            field=models.IntegerField(null=True, verbose_name='XLOC'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='yLoc',
            field=models.IntegerField(null=True, verbose_name='YLOC'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='city',
            field=models.CharField(max_length=50, verbose_name='CITY'),
        ),
    ]
